<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bill_detail extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bill_detail_model');
        $this->load->model('Order_bill_model');
        $this->load->model('Product_model');
    } 

    /*
     * Listing of bill_detail
     */
    function index($bill_id)
    {
        $data['bill_detail'] = $this->Bill_detail_model->get_all_bill_detail($bill_id);
        $data['bill'] = $this->Order_bill_model->get_bill($bill_id);
        $data['_view'] = 'bill_detail/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bill_detail
     */
    function add($bill_id)
    {   
        $this->form_validation->set_rules('productId',"productId",'required');
        $this->form_validation->set_rules('amount',"amount",'required');
        if($this->form_validation->run())
        {   
            $params = array(
                'amount' => $this->input->post('amount'),
				'productId' => $this->input->post('productId'),
				'bill_id' => $bill_id,
				'status' => $this->input->post('status'),
                'description' => $this->input->post('description'),
                'id'            => ObjectId()
            );
            
            $bill_detail_id = $this->Bill_detail_model->add_bill_detail($params);
            return redirect(base_url().'bill_detail/index/'.$bill_id);
        }
        else
        {            
            $data['product'] = $this->Product_model->get_all_product();
            $data['_view'] = 'bill_detail/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a bill_detail
     */
    function edit($id)
    {   
        // check if the bill_detail exists before trying to edit it
        $data['bill_detail'] = $this->Bill_detail_model->get_bill_detail($id);
        
        if(isset($data['bill_detail']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                    'amount' => $this->input->post('amount'),
					'productId' => $this->input->post('productId'),
					'bill_id' => $this->input->post('bill_id'),
					'status' => $this->input->post('status'),
					'description' => $this->input->post('description'),
                );

                $this->Bill_detail_model->update_bill_detail($id,$params);            
                redirect('bill_detail/index');
            }
            else
            {
                $data['product'] = $this->Product_model->get_all_product();
                $data['_view'] = 'bill_detail/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bill_detail you are trying to edit does not exist.');
    } 

    /*
     * Deleting bill_detail
     */
    // function remove()
    // {
    //     if(isset($_POST) && count($_POST) > 0){

    //         $dt = $_POST['data'];
        
    //         if($dt!=null){
    //         foreach($dt as $key =>$value){
    //             $this->Bill_detail_model->delete_bill_detail($value['id']);

    //         }
    //         return $this->Success(array(
    //             'message' => 'Xóa thành công!'
    //         ));
    //    }
    //     }
    //     return $this->Success(array(
    //         'isSuccess' =>false,
    //         'message' =>'Không tìm thấy sản phẩm!'
    //     ));
        
    // }

    function remove()
    {
        if(isset($_POST) && count($_POST) > 0){

            $dt = $_POST['data'];
            $params = array(
                'del' => 1,
            );
            if($dt!=null){
            foreach($dt as $key =>$value){
                $this->Bill_detail_model->update_bill_detail($value['id'],$params);

            }
            return $this->Success(array(
                'message' => 'Xóa thành công!'
            ));
       }
        }
        return $this->Success(array(
            'isSuccess' =>false,
            'message' =>'Không tìm thấy sản phẩm!'
        ));
        
    }
    
}
