<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
session_start();
if(isset($_SESSION["isadmin"])){
    if($_SESSION["isadmin"]!=1){
        header('Location: localhost/agile/auth');
        exit();
    }        
}
else if (!isset($_SESSION["isadmin"]) && !isset($_SESSION["user"])){
    header('Location: http://'.$_SERVER['HTTP_HOST'].'/agile/auth');
    exit();
}   

class Order extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_model');
    } 
     

    /*
     * Listing of product
     */
    function index()
    {
        $data['product'] = $this->Product_model->get_all_product();
        
        $data['_view'] = 'dashboard';
        $this->load->view('userlayouts/main',$data);
    }
}
