<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
session_start();

class Order extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_model');
        $this->load->model('Order_bill_model');
        $this->load->model('Bill_detail_model');
        $this->load->model('User_model');
    } 
     

    /*
     * Listing of product
     */
    function index()
    {
        $data['product'] = $this->Product_model->get_all_product();
        
        $data['_view'] = 'dashboard';
        $this->load->view('userlayouts/main',$data);
    }

    function add_order_bill()
    {            
        if(isset($_POST) && count($_POST) > 0){
            $dt=$_POST['data'];
        
            $totalPrice=0;
            foreach($dt as $key=>$item){
                if($item['Amount']){
                    $totalPrice+= $item['Amount']*$item['Price'];
                }
            }
           
                $bill_Id=ObjectId();
                $params = array(
                    'userId' => $_SESSION['user']->id,
                    'totalPrice' => $totalPrice,
                    'timestamp' =>date('Y-m-d H:i:s'),
                    'id'            =>  $bill_Id
                );       
                $bill_id = $this->Order_bill_model->add_bill($params);
                foreach($dt as $key=>$item){
                     if($item['Amount']){
                        $params = array(
                            'amount' => $item['Amount'],
                            'productId' =>  $item['id'],
                            'bill_id' => $bill_Id,
                            'id'            => ObjectId()
                        );
                        
                        $bill_detail_id = $this->Bill_detail_model->add_bill_detail($params);
                    }
                }
                    $email= $this->input->post('EMAIL');
                    if(!empty($email)){
                        $config = Array(
                            'protocol' => 'smtp',
                            'smtp_host' => 'ssl://smtp.googlemail.com',
                            'smtp_port' => 465,
                            'smtp_user' => 'fpohcmue@gmail.com', // change it to yours
                            'smtp_pass' => 'quangtientran1997', // change it to yours
                            'mailtype' => 'html',
                            'charset' => 'utf-8',
                            'wordwrap' => TRUE
                        );
                        
                                $this->load->library('email', $config);
                                $this->email->set_newline("\r\n");
                                $this->email->from('fpohcmue@gmail.com'); // change it to yours
                                $this->email->to($email);// change it to yours
                                $this->email->subject('Thông báo đặt món thành công');
                                $this->email->message("Bạn đã đặt món thành công");
                                if($this->email->send())
                            {
                                return $this->Success(array(
                                    'message' => 'Thành công!'
                                ));
    
                            }
                            else
                            {
                            show_error($this->email->print_debugger());
                            }
                    }
                    return $this->Success(array(
                        'isSuccess' => true,
                        'message' => 'Thành công!'
                    ));         
        }
        return $this->Success(array(
            'isSuccess' =>false,
            'message' =>'Thất bại!'
        ));               
    }   

    function details($id){
        $data['product'] = $this->Product_model->get_product($id);
        
        $data['_view'] = 'product/details';
        $this->load->view('userlayouts/main',$data);    
    }
}
