<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_model');
        // $this->load->model('Bill_detail_model');
    } 
     

    /*
     * Listing of product
     */
    function index()
    {
        $data['product'] = $this->Product_model->get_all_product();
        
        $data['_view'] = 'product/index';
        $this->load->view('layouts/main',$data);
    }
    
}
