<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get product by id
     */
    function get_product($id)
    {
      
        return $this->db->select('p.*')
        ->from('product p')
        ->where('p.id',$id)  
        // ->where('p.del !=',1) 
        // ->or_where('p.del is null')    
        ->where("(p.del != 1 OR p.del is null)")  
         ->get()
        ->row_array();
        // return $this->db->get_where('product',array('id'=>$id))->row_array();
    }
    function get_product_full($id)
    {
      
        return $this->db->select('p.*')
        ->from('product p')
        ->where('p.id',$id)  
        // ->where('p.del !=',1) 
        // ->or_where('p.del is null')    
        // ->where("(p.del != 1 OR p.del is null)")  
         ->get()
        ->row_array();
        // return $this->db->get_where('product',array('id'=>$id))->row_array();
    }
   
        
    /*
     * Get all product
     */
    function get_all_product()
    {
        // $this->db->order_by('id', 'desc');
        return $this->db->select('p.*')
        ->from('product p')
        // ->where('p.del !=',1) 
        // ->or_where('p.del is null') 
        ->where("(p.del != 1 OR p.del is null)")  
        ->order_by('id', 'desc')
         ->get()
        ->result_array();
        // $this->db->order_by('id', 'desc');
        // return $this->db->get('product')->result_array();
    }
        
    /*
     * function to add new product
     */
    function add_product($params)
    {
        $this->db->insert('product',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update product
     */
    function update_product($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('product',$params);
    }
    
    /*
     * function to delete product
     */
    function delete_product($id)
    {
        return $this->db->delete('product',array('id'=>$id));
    }
}
